=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2026.08.02 21:01:33 =~=~=~=~=~=~=~=~=~=~=~=
term len 9 0
R8#show run
Building configuration...

Current configuration : 933 bytes
!
version 12.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R8
!
boot-start-marker
boot-end-marker
!
!
no aaa new-model
memory-size iomem 5
no ip icmp rate-limit unreachable
!
!
ip cef
no ip domain lookup
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
ip tcp synwait-time 5
!
!
!
interface FastEthernet0/0
 ip address 217.1.38.8 255.255.255.0
 duplex auto
 speed auto
!
interface FastEthernet1/0
 ip address 192.168.5.200 255.255.255.0
 duplex auto
 speed auto
!
!
router ospf 109
 log-adjacency-changes
 area 1 stub
 network 192.168.5.0 0.0.0.255 area 1
 network 217.1.38.0 0.0.0.255 area 1
!
no ip http server
ip forward-protocol nd
!
!
!
no cdp log mismatch duplex
!
!
!
control-plane
!
!
!
!
!
!
!
!
!
line con 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
line aux 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
line vty 0 4
 login
!
!
end

R8#